image : mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test

variables:
    test: "spm-project-test"

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd spm-project-test"
        - "dotnet test"